home:
  name: Home
  view: false
  entities:
  - binary_sensor.alarm
  - cover.garage
  - light.garage
  - binary_sensor.ring_front_door_ding
  - binary_sensor.ring_front_door_motion
  - binary_sensor.den_tv
  - sensor.comed_current_hour_average_price
  - media_player.living_room__kitchen

mail:
  name: Mail
  view: false
  entities:
  - sensor.usps_mail
  - sensor.usps_packages
  - sensor.ups
  - sensor.fedex
  - camera.usps_mail

weather:
  name: Weather
  entities:
  - sensor.dark_sky_minutely_summary
  - sensor.dark_sky_humidity
  - sensor.dark_sky_daily_high_apparent_temperature
  - sensor.dark_sky_daily_low_apparent_temperature
  - sensor.dark_sky_hourly_summary
  - sensor.dark_sky_daily_summary
  - camera.weather_radar

basement:
  name: Basement
  entities:
  - light.desk_light
  - light.corner_light
  - light.salt_lamp
  - switch.switch
  - switch.candles
  - switch.dehumidifier

webcam:
  name: Webcam
  control: hidden
  entities:
  - binary_sensor.moto_x
  - switch.ip_webcam_torch
  - switch.ip_webcam_night_vision
  - camera.ip_webcam

pandorica:
  name: Pandorica
  entities:
  - binary_sensor.pandorica
  - script.pc_sleep
  - sensor.clicks
  - sensor.keys_pressed
  - sensor.steam_76561198039826665
  - media_player.plex_web_chrome

entertainment:
  name: Entertainment Center
  control: hidden
  entities:
  - script.tv_power
  - cover.volume
  - input_select.tv_input
  - media_player.amazon_fire_tv

pj_bedroom:
  name: Bedroom
  entities:
  - light.sengled_z01cia19nae26_0303d1dd_1
  - light.sengled_e11g13_0306449a_1
  - switch.bedroom_fan
  - light.sengled_e11g13_0306574f_1
  - group.pj_bedroom_badges
  - media_player.pjs_chromecast
  - media_player.phils_room

pj_bedroom_badges:
  entities:
  - binary_sensor.penn
  - binary_sensor.steam_link

pj_bedroom_scenes:
  name: Scenes
  control: hidden
  entities:
  - scene.high_bedroom
  - scene.low_bedroom
  - scene.bedtime

pj_bedroom_auto:
  name: Automation
  control: hidden
  entities:
  - automation.turn_off_fan_in_2_hours
  - automation.bedroom__closet_off_in_2_minutes

pj_phone:
  name: Phone
  entities:
  - device_tracker.phone_s7
  - group.pj_phone_badges
  - media_player.galaxy_s7

pj_phone_badges:
  name: Phone Badges
  entities:
  - sensor.battery
  - binary_sensor.pebble
  - sensor.ringer
  - sensor.notifications
  - sensor.media

docker:
  name: Docker
  entities:
  - switch.docker_portainer
  - switch.docker_firetvserver
  - switch.docker_nextcloud
  - switch.docker_mcmyadmin2
  - switch.docker_plex
  - switch.docker_transmission
  - group.transmission_badges

transmission_badges:
  entities:
  - sensor.transmission_down_speed
  - sensor.transmission_up_speed

venus:
  name: System
  entities:
  - sensor.disk_free_mntsulfur
  - sensor.disk_free_homephil
  - sensor.ram_free
  - sensor.since_last_boot

pihole:
  name: Pi-Hole
  entities:
  - sensor.pihole_ads_blocked_today
  - sensor.pihole_dns_queries_today
  - sensor.pihole_dns_unique_clients

homeassistant:
  name: Home Assistant
  entities:
  - updater.updater
  - sensor.current_version
  - sensor.ha_uptime
  - script.zha_permit
  - script.zwave_add
  - script.zwave_heal
  - zwave.sigma_designs_uzb_zwave_usb_adapter
  - zwave.ecolink_garage_door_tilt_sensor
  - zwave._

office:
  name: Office
  entities:
  - sensor.steam_76561198083742776
  - binary_sensor.xerox

######################
######## Views #######
######################
#default_view:
home_view:
  name: Home
  icon: mdi:home
  view: yes
  entities:
  - device_tracker.iphone
  - device_tracker.phone_s7
  - binary_sensor.mom_iphone
  - group.home
  - group.mail
  - group.weather

bedroom_view:
  name: Bedroom
  icon: mdi:hotel
  view: yes
  entities:
  - sensor.steps
  - binary_sensor.visonic_mct340_e_0b02b650_1
  - binary_sensor.visonic_mct340_e_0b02bcb4_1
  - binary_sensor.visonic_mct340_e_0b02b43c_1
  - group.pj_bedroom
  - group.pj_phone
  - group.pj_status
  - group.pj_bedroom_scenes
  - group.pj_bedroom_auto

basement_view:
  name: Basement
  icon: mdi:television
  view: yes
  entities:
  - sensor.feed_the_beats
  - binary_sensor.ps3
  - binary_sensor.switch
  - binary_sensor.wii_u
  - binary_sensor.xbox_360
  - group.pandorica
  - group.basement
  - group.entertainment
  - group.webcam
  - media_player.aftt
  - media_player.spotify

server_view:
  name: Server
  icon: mdi:server
  view: yes
  entities:
  - group.venus
  - group.docker
  - group.pihole
  - group.homeassistant
  - sensor.speedtest_ping
  - sensor.fastcom_download
  - sensor.speedtest_download
  - sensor.speedtest_upload
  - group.office