- alias: Notify - If GaragePi is down
  trigger:
    platform: state
    entity_id: binary_sensor.garagepi
    to: "off"
  action:
      - service: notify.pj_phone
        data:
          message: "Garage can only be opened with physical buttons."
          title: "GaragePi is Offline."

- alias: Notify - If GaragePi is back
  trigger:
    platform: state
    entity_id: binary_sensor.garagepi
    to: "on"
  action:
      - service: notify.pj_phone
        data:
          message: "Garage can be opened with Home Assistant and physical buttons."
          title: "GaragePi is back online."