- alias: Notify - Start
  trigger:
    platform: homeassistant
    event: start
  action:
      - service: notify.pj_phone
        data:
          message: "Back to business"
          title: "Home Assistant Restarted."