- alias: PC is Snoozed
  trigger:
    platform: state
    entity_id: sensor.steam_76561198039826665
    to: 'Snooze'
  action:
      - service: notify.pj_phone
        data:
          message: "You should probably put it to sleep."
          title: "Pandorica is idle"