- alias: PJ has left
  trigger:
    platform: state
    entity_id: device_tracker.phone_s7
    to: "not_home"
  action:
      - service: notify.pj_phone
        data:
          message: "Turning off Basement and Bedroom"
          title: "PJ has left."
      - service: homeassistant.turn_off
        data:
          entity_id: group.basement
      - service: homeassistant.turn_off
        data:
          entity_id: group.pj_bedroom

- alias: PJ is home
  trigger:
    platform: state
    entity_id: device_tracker.phone_s7
    to: "home"
  action:
      - service: notify.pj_phone
        data:
          message: "-"
          title: "Welcome Home."


- alias: Notify - Phil is home
  trigger:
    platform: state
    entity_id: device_tracker.iphone
    to: "home"
  action:
      - service: notify.pj_phone
        data:
          message: "-"
          title: "Phil is home."

- alias: Notify - Phil is away
  trigger:
    platform: state
    entity_id: device_tracker.iphone
    to: "not_home"
  action:
      - service: notify.pj_phone
        data:
          message: "-"
          title: "Phil has left."