- platform: usps
  username: !secret usps_user
  password: !secret usps_pass
- platform: ups
  username: !secret ups_user
  password: !secret ups_pass
- platform: fedex
  username: !secret fedex_user
  password: !secret fedex_pass