- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
  - apparent_temperature
  - humidity
  - minutely_summary
  - hourly_summary
  - daily_summary
  - apparent_temperature_max
  - apparent_temperature_min